// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrig34xGCrjjRk9YLiHZDcuzj9ytb7efk',
    appId: '1:254151195854:web:5d6098b983fc87aa8fe49f',
    messagingSenderId: '254151195854',
    projectId: 'motionx-fitnesstracker',
    authDomain: 'motionx-fitnesstracker.firebaseapp.com',
    storageBucket: 'motionx-fitnesstracker.firebasestorage.app',
    measurementId: 'G-VZX9VJ0HYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxNBYfCz7zpIffGXbQ9oeXS2x_Ba8GBg',
    appId: '1:254151195854:android:a661365538af0d738fe49f',
    messagingSenderId: '254151195854',
    projectId: 'motionx-fitnesstracker',
    storageBucket: 'motionx-fitnesstracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiE56JxFG92p8hJ3hLU2mjY_EWAcmTTE',
    appId: '1:254151195854:ios:2e49d71104ac9d788fe49f',
    messagingSenderId: '254151195854',
    projectId: 'motionx-fitnesstracker',
    storageBucket: 'motionx-fitnesstracker.firebasestorage.app',
    iosBundleId: 'com.motionx.fitnesstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiE56JxFG92p8hJ3hLU2mjY_EWAcmTTE',
    appId: '1:254151195854:ios:235eb0272c829c5e8fe49f',
    messagingSenderId: '254151195854',
    projectId: 'motionx-fitnesstracker',
    storageBucket: 'motionx-fitnesstracker.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrig34xGCrjjRk9YLiHZDcuzj9ytb7efk',
    appId: '1:254151195854:web:a1e852a92b34a1488fe49f',
    messagingSenderId: '254151195854',
    projectId: 'motionx-fitnesstracker',
    authDomain: 'motionx-fitnesstracker.firebaseapp.com',
    storageBucket: 'motionx-fitnesstracker.firebasestorage.app',
    measurementId: 'G-08P5CXBJL2',
  );
}
